---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitoring.oswatcher.io
  resources:
  - osstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.oswatcher.io
  resources:
  - osstatuses/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.oswatcher.io
  resources:
  - osstatuses/status
  verbs:
  - get
  - patch
  - update
